version: "3"

services:
  pickem_pgdb:
    image: postgres:9.6.6-alpine
    environment:
      POSTGRES_USER: pickem
      POSTGRES_PASSWORD: pickem_password
    ports:
      - "5432:5432"
  pickem_redis:
    image: redis:4
    ports:
      - "6379:6379"
